cargo-features = ["rename-dependency"]

[package]
name = "dtoa"
version = "0.4.3" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Fast functions for printing floating-point primitives to an io::Write"
repository = "https://github.com/dtolnay/dtoa"
documentation = "https://github.com/dtolnay/dtoa"
categories = ["value-formatting"]
readme = "README.md"
exclude = ["performance.png"]

[badges]
travis-ci = { repository = "dtolnay/dtoa" }

[dev-dependencies]
dtolnay_ryu = { package = "ryu", git = "https://github.com/dtolnay/ryu" }
ryu = "0.1.1"
float_fast_print = "0.1.2"
